github_checks:
    annotations: false

ignore:
    - "**/tests/**"
    - "**/*.sh"

coverage:
    status:
        project:
            default:
                informational: true
        patch:
            default:
                informational: true
