# Local-development services for refinebio.

name: refinebio

services:
  postgres:
    image: postgres:9.6.6
    container_name: drdb
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./volumes_postgres:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: dres
    platform: linux/amd64
    environment:
      discovery.type: single-node
      indices.query.bool.max_clause_count: 16384
    ports:
      - "9200:9200"
      - "9300:9300"
