FROM python:3.5-slim

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

COPY foreman/requirements.txt .

RUN pip install -r requirements.txt

COPY data_models/dist/data-refinery-models-* data_models/

# Get the latest version from the dist directory.
RUN pip install data_models/$(ls data_models -1 | tail -1)

COPY foreman/ .

USER user

CMD ./manage.py start
