FROM python:3.5-slim

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

ENV CELERY_VERSION 4.0.2

COPY workers/requirements.in .

RUN pip install pip-tools && \
    pip-compile requirements.in && \
    pip install -r requirements.txt

COPY data_models/dist/* .

RUN pip install --user bioinformatics-mill-models-*

COPY workers/ .

USER user

CMD ./manage.py shell < master.py
