FROM python:3.5-slim

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

ENV CELERY_VERSION 4.0.2

COPY data_models/requirements.in .

RUN pip install pip-tools && \
    pip-compile requirements.in && \
    pip install -r requirements.txt

COPY data_models/ .

USER user

CMD ./manage.py makemigrations && ./manage.py migrate
