FROM python:3.6.1-slim

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

RUN pip install --upgrade pip

COPY api/requirements.txt .

RUN pip install -r requirements.txt

COPY common/dist/data-refinery-common-* common/

# Get the latest version from the dist directory.
RUN pip install \
    common/$(ls common -1 | sort --version-sort | tail -1)

COPY api/ .

USER user

EXPOSE 8000

ENTRYPOINT []
