# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('source_type', models.CharField(max_length=256)),
                ('size_in_bytes', models.IntegerField()),
                ('download_url', models.CharField(max_length=256)),
                ('raw_format', models.CharField(max_length=256)),
                ('processed_format', models.CharField(max_length=256)),
                ('processor_required', models.IntegerField()),
                ('accession_code', models.CharField(max_length=256)),
                ('internal_location', models.CharField(max_length=256)),
                ('organism', models.IntegerField()),
                ('status', models.CharField(choices=[(b'NEW', b'New'), (b'DOWNLOADED', b'Downloaded'), (b'PROCESSED', b'Proccessed')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
