# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatics_mill_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='internal_location',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='processed_format',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='raw_format',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='downloaderjob',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='downloaderjob',
            name='num_retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='downloaderjob',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='processorjob',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='processorjob',
            name='num_retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processorjob',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='surveyjob',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='surveyjob',
            name='replication_ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='surveyjob',
            name='replication_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='surveyjob',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
