renv::install("data.table@1.11.0")
renv::install("getopt@1.20.3")
renv::install("optparse@1.4.4")
renv::install("rlang@0.3.1")
renv::install("crayon@1.3.4")
renv::install("assertthat@0.2.1")
renv::install("cli@1.1.0")
renv::install("fansi@0.4.0")
renv::install("utf8@1.1.4")
renv::install("digest@0.6.18")
renv::install("glue@1.3.1")
renv::install("pillar@1.3.1")
renv::install("pkgconfig@2.0.2")
renv::install("pillar@1.3.1")
renv::install("tibble@2.0.1")
renv::install("lazyeval@0.2.1")
renv::install("Rcpp@1.0.7")
renv::install("magrittr@1.5")
renv::install("purrr@0.3.3")
renv::install("tidyselect@0.2.5")
renv::install("R6@2.4.0")
renv::install("lifecycle@1.0.3")
renv::install("tibble@2.0.1")
renv::install("stringi@1.4.3")
renv::install("stringr@1.4.0")
renv::install("plyr@1.8.4")
renv::install("reshape2@1.4.3")
renv::install("bit@1.1-14")
renv::install("bit64@0.9-7")
renv::install("prettyunits@1.0.2")
renv::install("blob@1.1.1")
renv::install("DBI@1.0.0")
renv::install("memoise@2.0.1")
renv::install("RSQLite@2.1.1")
renv::install("ff@2.2-14")
renv::install("dplyr@1.0.2")
renv::install("readr@1.3.1")
renv::install("rlang@1.0.6")
renv::install("ellipsis@0.3.2")

renv::install(
    "oligo",
    "oligoClasses",
    "AnnotationDbi",
    "illuminaHumanv1.db",
    "illuminaHumanv2.db",
    "illuminaHumanv3.db",
    "illuminaHumanv4.db",
    "illuminaMousev1.db",
    "illuminaMousev1p1.db",
    "illuminaMousev2.db",
    "illuminaRatv1.db"
)
