# Generated from cranlock
options(warn=2)
options(Ncpus=parallel::detectCores())
options(repos=structure(c(CRAN="https://cran.revolutionanalytics.com")))
devtools::install_version('getopt', version='1.20.3')
devtools::install_version('optparse', version='1.4.4')
devtools::install_version('rjson', version='0.2.19')
devtools::install_version('R6', version='2.4.0')
devtools::install_version('pkgconfig', version='2.0.2')
devtools::install_version('rlang', version='0.4.0')
devtools::install_version('zeallot', version='0.1.0')
devtools::install_version('backports', version='1.1.4')
devtools::install_version('glue', version='1.3.1')
devtools::install_version('digest', version='0.6.19')
devtools::install_version('vctrs', version='0.1.0')
devtools::install_version('hms', version='0.4.2')
devtools::install_version('Rcpp', version='1.0.1')
devtools::install_version('assertthat', version='0.2.1')
devtools::install_version('crayon', version='1.3.4')
devtools::install_version('cli', version='1.1.0')
devtools::install_version('utf8', version='1.1.4')
devtools::install_version('fansi', version='0.4.0')
devtools::install_version('pillar', version='1.4.2')
devtools::install_version('tibble', version='2.1.3')
devtools::install_version('readr', version='1.1.1')
