FROM ubuntu:16.04

RUN apt-get update -qq
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:apt-fast/stable
RUN apt-get update -qq
RUN apt-get -y install apt-fast

RUN \
  apt-fast update -qq && \
  apt-fast install -y lsb-release && \
  echo "deb http://archive.linux.duke.edu/cran/bin/linux/ubuntu $(lsb_release -sc)/" \
      >> /etc/apt/sources.list.d/added_repos.list && \
  apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E084DAB9 && \
  apt-fast update -qq && \
  apt-fast install -y \
  ed \
  git \
  python3 \
  python3-pip \
  r-base \
  r-base-dev \
  libpq-dev \
  libxml2-dev \
  libssl-dev \
  libcurl4-openssl-dev \
  libpq-dev \
  curl \
  wget && \
  rm -rf /var/lib/apt/lists/*

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

ENV R_LIBS "/usr/local/lib/R/site-library"

COPY workers/install_affy_only.R .

RUN Rscript install_affy_only.R

RUN pip3 install --upgrade pip

COPY config config

COPY common/requirements.txt .

RUN pip3 install -r requirements.txt

# Install this rpy2 here instead of via requirements.txt because
# pip-compile throws an error for it.
RUN pip3 install rpy2

COPY common/ .

USER user

ENTRYPOINT [""]
