FROM ccdlstaging/dr_base:latest

# Fail in case of an error at any stage in the pipe.
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

WORKDIR /home/user

COPY common/requirements.txt .
RUN pip install --ignore-installed --no-cache-dir -r requirements.txt

COPY common/ .
COPY config config

ARG SYSTEM_VERSION
ENV SYSTEM_VERSION=$SYSTEM_VERSION

USER user

ENTRYPOINT []
