FROM ubuntu:18.04

RUN apt-get update -qq
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:apt-fast/stable
RUN apt-get update -qq
RUN apt-get -y install apt-fast

# Prevent tzdata from prompting us for a timezone and hanging the build.
ENV DEBIAN_FRONTEND=noninteractive

# The packages related to R are somewhat weird, see the README for more details.

COPY workers/CRAN.gpg .
RUN \
  apt-fast update -qq && \
  apt-get install -y apt-transport-https && \
  apt-fast install -y lsb-release && \
  echo "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/" \
      >> /etc/apt/sources.list.d/added_repos.list && \
  apt-key add CRAN.gpg && \
  apt-fast update -qq && \
  apt-fast install -y \
  ed \
  git \
  python3 \
  python3-pip \
  python3-dev \
  r-base-core \
  r-base-dev \
  libpq-dev \
  libxml2-dev \
  libssl-dev \
  libcurl4-openssl-dev \
  curl \
  wget && \
  rm -rf /var/lib/apt/lists/*
RUN rm CRAN.gpg

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

ENV R_LIBS "/usr/local/lib/R/site-library"

COPY common/install_devtools.R .

RUN Rscript install_devtools.R

COPY workers/install_bioc.R .

RUN Rscript install_bioc.R

COPY workers/install_affy_only.R .

RUN Rscript install_affy_only.R

# Source: https://github.com/thisbejim/Pyrebase/issues/87#issuecomment-354452082
# For whatever reason this worked and 'en_US.UTF-8' did not.
ENV LANG C.UTF-8

COPY config config

COPY common/requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

# Install this rpy2 here instead of via requirements.txt because
# pip-compile throws an error for it.
RUN pip3 install rpy2==3.4.5

COPY common/ .

ARG SYSTEM_VERSION

ENV SYSTEM_VERSION $SYSTEM_VERSION

USER user

ENTRYPOINT [""]
