FROM ccdlstaging/dr_base:latest

# Fail in case of an error at any stage in the pipe.
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Source: https://github.com/thisbejim/Pyrebase/issues/87#issuecomment-354452082
# For whatever reason this worked and 'en_US.UTF-8' did not.
ENV LANG=C.UTF-8

WORKDIR /home/user

ENV R_LIBS=/usr/local/lib/R/site-library

COPY workers/R/dependencies/install_bioc.R .
RUN Rscript install_bioc.R

COPY workers/R/dependencies/affymetrix/install_affy_only.R .
RUN Rscript install_affy_only.R

COPY config config

COPY common/requirements.txt .
RUN pip3 install --ignore-installed -r requirements.txt && \
    # Install this rpy2 here instead of via requirements.txt because
    # pip-compile throws an error for it.
    pip3 install rpy2==3.4.5 && \
    rm -rf /root/.cache

COPY common/ .

ARG SYSTEM_VERSION
ENV SYSTEM_VERSION=$SYSTEM_VERSION

USER user

ENTRYPOINT []
