FROM python:3.5

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

ENV CELERY_VERSION 4.0.2

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

USER user

ENTRYPOINT ["python3.5", "manage.py", "test", "--no-input"]
