# Generated by Django 2.1.2 on 2018-10-04 20:16

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computationalresult",
            name="commands",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="computationalresultannotation",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="protocol_description",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="publication_authors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="experimentannotation",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="steps",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="processor",
            name="environment",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="sample",
            name="protocol_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="sampleannotation",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
