# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaderjob',
            name='worker_version',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='processorjob',
            name='worker_version',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
