# Generated by Django 2.0.2 on 2018-04-09 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='source_last_updated',
            new_name='source_last_modified',
        ),
        migrations.RemoveField(
            model_name='processorjob',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='surveyjob',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='surveyjobkeyvalue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='surveyjobkeyvalue',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='downloaderjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='downloaderjob',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='downloaderjob',
            name='original_files',
            field=models.ManyToManyField(through='data_refinery_common.DownloaderJobOriginalFileAssociation', to='data_refinery_common.OriginalFile'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='samples',
            field=models.ManyToManyField(through='data_refinery_common.ExperimentSampleAssociation', to='data_refinery_common.Sample'),
        ),
        migrations.AddField(
            model_name='organism',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='organism',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='processorjob',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='processorjob',
            name='original_files',
            field=models.ManyToManyField(through='data_refinery_common.ProcessorJobOriginalFileAssociation', to='data_refinery_common.OriginalFile'),
        ),
        migrations.AddField(
            model_name='sample',
            name='results',
            field=models.ManyToManyField(through='data_refinery_common.SampleResultAssociation', to='data_refinery_common.ComputationalResult'),
        ),
        migrations.AddField(
            model_name='surveyjob',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='processorjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='surveyjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
