# Generated by Django 2.0.2 on 2018-03-14 19:34

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentannotation',
            name='key',
        ),
        migrations.RemoveField(
            model_name='experimentannotation',
            name='value',
        ),
        migrations.RemoveField(
            model_name='sampleannotation',
            name='key',
        ),
        migrations.RemoveField(
            model_name='sampleannotation',
            name='value',
        ),
        migrations.AddField(
            model_name='compultationalresultannotation',
            name='is_ccdl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='has_publication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='protocol_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experiment',
            name='publication_doi',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='experiment',
            name='publication_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pubmed_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='experiment',
            name='source_first_published',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='experiment',
            name='source_last_updated',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='experiment',
            name='submitter_institution',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='experimentannotation',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
        migrations.AddField(
            model_name='experimentannotation',
            name='is_ccdl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampleannotation',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
        migrations.AddField(
            model_name='sampleannotation',
            name='is_ccdl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='computationalresult',
            name='command_executed',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='computationalresult',
            name='program_version',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='downloaderjob',
            name='failure_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='platform_accession_code',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='platform_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processorjob',
            name='failure_reason',
            field=models.TextField(null=True),
        ),
    ]
