# Generated by Django 2.0.2 on 2018-07-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0002_auto_20180629_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismindex',
            name='salmon_version',
            field=models.CharField(default='0.9.1', max_length=255),
        ),
        migrations.AlterField(
            model_name='organismindex',
            name='source_version',
            field=models.CharField(default='92', max_length=255),
        ),
    ]
