# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0002_auto_20170727_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaderjob',
            name='failure_reason',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='downloaderjob',
            name='retried_job',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to='data_refinery_common.DownloaderJob'),
        ),
        migrations.AddField(
            model_name='processorjob',
            name='failure_reason',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='processorjob',
            name='retried_job',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to='data_refinery_common.ProcessorJob'),
        ),
    ]
