# Generated by Django 2.0.2 on 2018-04-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0002_auto_20180409_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='source_first_published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='source_last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
