# Generated by Django 2.1.2 on 2018-10-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0002_auto_20181004_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyjob',
            name='num_retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyjob',
            name='retried',
            field=models.BooleanField(default=False),
        ),
    ]
