# Generated by Django 2.0.2 on 2018-07-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0003_auto_20180709_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismindex',
            name='s3_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
