# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0003_auto_20170809_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=1024)),
                ('download_url', models.CharField(max_length=4096)),
                ('raw_format', models.CharField(max_length=256, null=True)),
                ('processed_format', models.CharField(max_length=256, null=True)),
                ('internal_location', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.RemoveField(
            model_name='batch',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='internal_location',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='processed_format',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='raw_format',
        ),
        migrations.AlterField(
            model_name='batch',
            name='size_in_bytes',
            field=models.BigIntegerField(),
        ),
        migrations.AddField(
            model_name='file',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Batch'),
        ),
    ]
