# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0004_auto_20171004_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='size_in_bytes',
        ),
        migrations.AddField(
            model_name='file',
            name='size_in_bytes',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
