# Generated by Django 2.0.2 on 2018-07-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0004_organismindex_s3_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorjob',
            name='ram_amount',
            field=models.IntegerField(default=2048),
        ),
    ]
