# Generated by Django 2.1.2 on 2018-10-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0004_auto_20181026_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyjob',
            name='num_retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyjob',
            name='retried',
            field=models.BooleanField(default=False),
        ),
    ]
