# Generated by Django 2.0.2 on 2018-07-16 18:17

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0005_processorjob_ram_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
            ],
            options={
                'db_table': 'pipelines',
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=64)),
                ('docker_image', models.CharField(max_length=255)),
                ('environment', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'db_table': 'processors',
            },
        ),
        migrations.RemoveField(
            model_name='computationalresult',
            name='command_executed',
        ),
        migrations.RemoveField(
            model_name='computationalresult',
            name='program_version',
        ),
        migrations.RemoveField(
            model_name='computationalresult',
            name='system_version',
        ),
        migrations.AddField(
            model_name='computationalresult',
            name='commands',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
        migrations.AlterUniqueTogether(
            name='processor',
            unique_together={('name', 'version')},
        ),
        migrations.AddField(
            model_name='computationalresult',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Processor'),
        ),
    ]
