# Generated by Django 2.1.2 on 2018-11-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0005_auto_20181030_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyjob',
            name='nomad_job_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='surveyjob',
            name='ram_amount',
            field=models.IntegerField(default=256),
        ),
    ]
