# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0005_auto_20171004_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='experiment_accession_code',
            field=models.CharField(max_length=64),
        ),
    ]
