# Generated by Django 2.0.2 on 2018-07-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0006_auto_20180716_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalfile',
            name='s3_bucket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='originalfile',
            name='s3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='computedfile',
            name='s3_bucket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='computedfile',
            name='s3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
