# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-08 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0007_compultationalresultannotation_computationalresult_experiment_experimentresultassociation_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow, editable=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
