# Generated by Django 2.1.2 on 2019-01-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0008_auto_20190104_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='sha1',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dataset',
            name='size_in_bytes',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
