# Generated by Django 2.1.2 on 2019-01-08 20:20
# Modified by Rich

import django.contrib.postgres.fields
from django.db import migrations, models

def update_cached_values(apps, schema_editor):
    """ """

    Experiment = apps.get_model('data_refinery_common', 'Experiment')
    for experiment in Experiment.objects.all():
        experiment.update_num_samples()
        experiment.update_sample_metadata_fields()
        experiment.update_organism_names()
        experiment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0008_auto_20190104_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='num_processed_samples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='num_total_samples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='organism_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='experiment',
            name='sample_metadata_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='originalfile',
            name='downloader_jobs',
            field=models.ManyToManyField(through='data_refinery_common.DownloaderJobOriginalFileAssociation', to='data_refinery_common.DownloaderJob'),
        ),
        migrations.AddField(
            model_name='originalfile',
            name='processor_jobs',
            field=models.ManyToManyField(through='data_refinery_common.ProcessorJobOriginalFileAssociation', to='data_refinery_common.ProcessorJob'),
        ),
        migrations.AddField(
            model_name='sample',
            name='experiments',
            field=models.ManyToManyField(through='data_refinery_common.ExperimentSampleAssociation', to='data_refinery_common.Experiment'),
        ),
        migrations.RunPython(update_cached_values)
    ]
