# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-08 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0008_auto_20180208_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='platform_accession_code',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='platform_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
