# Generated by Django 2.0.2 on 2018-08-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0009_auto_20180802_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedfile',
            name='is_qn_target',
            field=models.BooleanField(default=False),
        ),
    ]
