# Generated by Django 2.1.2 on 2019-01-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0009_auto_20190111_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='sha1',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
