# Generated by Django 2.0.2 on 2018-08-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0010_auto_20180806_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedfile',
            name='samples',
            field=models.ManyToManyField(through='data_refinery_common.SampleComputedFileAssociation', to='data_refinery_common.Sample'),
        ),
    ]
