# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0010_auto_20180209_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='has_prederived',
            new_name='has_derived',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='source_url',
            new_name='source_archive_url',
        ),
        migrations.AddField(
            model_name='experimentsampleassociation',
            name='experiment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Experiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentsampleassociation',
            name='sample',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Sample'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='source_filename',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
