# Generated by Django 2.1.5 on 2019-01-29 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0010_auto_20190125_1655"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfile",
            name="compendia_organism",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_refinery_common.Organism",
            ),
        ),
        migrations.AddField(
            model_name="computedfile",
            name="compendia_version",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computedfile",
            name="is_compendia",
            field=models.BooleanField(default=False),
        ),
    ]
