# Generated by Django 2.0.2 on 2018-08-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0011_computedfile_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='scale_by',
            field=models.CharField(choices=[('NONE', 'None'), ('MINMAX', 'Minmax'), ('STANDARD', 'Standard'), ('ROBUST', 'Robust')], default='NONE', max_length=255),
        ),
    ]
