# Generated by Django 2.0.2 on 2018-08-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0012_auto_20180810_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processorjob',
            old_name='data_sets',
            new_name='datasets',
        ),
    ]
