# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0012_auto_20180209_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='accession_code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='accession_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
