# Generated by Django 2.0.2 on 2018-08-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0012_auto_20180810_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedfile',
            name='is_qn_target',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='quantile_normalize',
            field=models.BooleanField(default=True),
        ),
    ]
