# Generated by Django 2.0.2 on 2018-08-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0013_auto_20180817_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorjob',
            name='volume_index',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
