# Generated by Django 2.0.2 on 2018-08-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0013_auto_20180817_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedfile',
            name='is_qn_target',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='quantile_normalize',
            field=models.BooleanField(default=True),
        ),
    ]
