# Generated by Django 2.0.2 on 2018-08-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0013_auto_20180817_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismindex',
            name='absolute_directory_path',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
