# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0013_auto_20180209_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organism',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='updated_at',
        ),
    ]
