# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0014_auto_20180209_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Organism'),
        ),
    ]
