# Generated by Django 2.1.5 on 2019-03-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0015_dataset_email_ccdl_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalfile',
            name='downloader_jobs',
            field=models.ManyToManyField(through='data_refinery_common.DownloaderJobOriginalFileAssociation', to='data_refinery_common.DownloaderJob'),
        ),
        migrations.AddField(
            model_name='originalfile',
            name='processor_jobs',
            field=models.ManyToManyField(through='data_refinery_common.ProcessorJobOriginalFileAssociation', to='data_refinery_common.ProcessorJob'),
        ),
        migrations.AddField(
            model_name='sample',
            name='experiments',
            field=models.ManyToManyField(through='data_refinery_common.ExperimentSampleAssociation', to='data_refinery_common.Experiment'),
        ),
    ]
