# Generated by Django 2.0.2 on 2018-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0015_processorjob_volume_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaderjob',
            name='no_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processorjob',
            name='no_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyjob',
            name='no_retry',
            field=models.BooleanField(default=False),
        ),
    ]
