# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0016_auto_20180209_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloaderjob',
            name='batches',
        ),
        migrations.RemoveField(
            model_name='downloaderjob',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='downloaderjob',
            name='retried_job',
        ),
        migrations.RemoveField(
            model_name='downloaderjob',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='downloaderjob',
            name='sample',
            field=models.ForeignKey(default='', max_length=256, on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Sample'),
            preserve_default=False,
        ),
    ]
