# Generated by Django 2.0.2 on 2018-09-05 17:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0016_auto_20180824_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='protocol_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='protocol_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
