# Generated by Django 2.0.2 on 2018-08-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0016_auto_20180824_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismindex',
            name='absolute_directory_path',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
