# Generated by Django 2.0.2 on 2018-09-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0017_auto_20180906_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismindex',
            name='absolute_directory_path',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
