# Generated by Django 2.1.5 on 2019-03-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0017_auto_20190312_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaderjob',
            name='ram_amount',
            field=models.IntegerField(default=1024),
        ),
    ]
