# Generated by Django 2.0.2 on 2018-02-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0017_auto_20180209_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloaderjob',
            name='sample',
        ),
        migrations.AddField(
            model_name='downloaderjob',
            name='experiment',
            field=models.ForeignKey(default='', max_length=256, on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Experiment'),
            preserve_default=False,
        ),
    ]
