# Generated by Django 2.0.2 on 2018-02-12 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0018_auto_20180209_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Experiment')),
            ],
            options={
                'db_table': 'experiment_annotations',
            },
        ),
    ]
