# Generated by Django 2.0.2 on 2018-02-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0020_experiment_source_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorJobSampleAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.ProcessorJob')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Sample')),
            ],
            options={
                'db_table': 'processorjob_sample_associations',
            },
        ),
    ]
