# Generated by Django 2.0.2 on 2018-09-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0020_experiment_protocol_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computedfile',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'base_manager_name': 'public_objects', 'get_latest_by': 'created_at'},
        ),
    ]
