# Generated by Django 2.0.2 on 2018-02-13 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0021_processorjobsampleassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('sha1', models.CharField(max_length=64)),
                ('s3_bucket', models.CharField(max_length=64)),
                ('s3_key', models.CharField(max_length=64)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'computed_files',
            },
        ),
        migrations.AddField(
            model_name='computationalresult',
            name='command_executed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='computationalresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='computationalresult',
            name='is_ccdl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='computationalresult',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computationalresult',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='computationalresult',
            name='system_version',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computedfile',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.ComputationalResult'),
        ),
    ]
