# Generated by Django 2.1.8 on 2019-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0022_auto_20190607_1505'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='downloaderjob',
            index=models.Index(fields=['created_at', 'start_time', 'end_time'], name='downloader_jobs_created_at'),
        ),
        migrations.AddIndex(
            model_name='processorjob',
            index=models.Index(fields=['created_at', 'start_time', 'end_time'], name='processor_jobs_created_at_time'),
        ),
        migrations.AddIndex(
            model_name='downloaderjob',
            index=models.Index(fields=['worker_id'], name='downloader__worker__d0aba6_idx'),
        ),
    ]
