# Generated by Django 2.1.8 on 2019-06-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0022_auto_20190607_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology_term', models.CharField(max_length=256, unique=True)),
                ('human_readable_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'ontology_terms',
            },
        ),
    ]
