# Generated by Django 2.0.2 on 2018-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0022_auto_20180213_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedfile',
            name='absolute_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='computedfile',
            name='size_in_bytes',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
