# Generated by Django 2.0.2 on 2018-02-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0023_auto_20180213_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='source_absolute_file_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
