# Generated by Django 2.0.2 on 2018-02-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0024_sample_source_absolute_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='has_derived',
        ),
    ]
