# Generated by Django 2.1.8 on 2019-08-05 19:52

from django.db import migrations, models
import django.db.models.deletion

def update_organisms_qn_targets(apps, schema_editor):
    """ Set the latest qn_target to each organism. """
    Organism = apps.get_model('data_refinery_common', 'Organism')

    for organism in Organism.objects.all():
        result_annotation = ComputationalResultAnnotation.objects.all()\
                                .filter(data__organism_id=organism.id, data__is_qn=True)\
                                .order_by('-created_at')\
                                .first() # https://docs.djangoproject.com/en/dev/ref/models/querysets/#first
        if result_annotation:
            organism.qn_target = result_annotation.result
            organism.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0025_downloaderjob_volume_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='qn_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_refinery_common.ComputationalResult'),
        ),
        migrations.RunPython(update_organisms_qn_targets)
    ]

