# Generated by Django 2.0.2 on 2018-02-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0027_auto_20180214_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalfile',
            name='has_raw',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='originalfile',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='originalfile',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
