# Generated by Django 2.1.8 on 2019-08-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0028_auto_20190802_1957'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='originalfile',
            index=models.Index(fields=['filename'], name='original_fi_filenam_d0ea88_idx'),
        ),
        migrations.AddIndex(
            model_name='originalfile',
            index=models.Index(fields=['source_filename'], name='original_fi_source__6b971c_idx'),
        ),
    ]
