# Generated by Django 2.0.2 on 2018-02-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0028_auto_20180214_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloaderjob',
            name='experiment',
        ),
        migrations.AddField(
            model_name='downloaderjob',
            name='original_file',
            field=models.ForeignKey(default='', max_length=256, on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.OriginalFile'),
            preserve_default=False,
        ),
    ]
