# Generated by Django 2.0.2 on 2018-02-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0029_auto_20180214_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloaderJobOriginalFileAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloader_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.DownloaderJob')),
            ],
            options={
                'db_table': 'downloaderjob_originalfile_associations',
            },
        ),
        migrations.DeleteModel(
            name='ExperimentResultAssociation',
        ),
        migrations.RenameField(
            model_name='originalfile',
            old_name='source_archive_url',
            new_name='source_url',
        ),
        migrations.AddField(
            model_name='originalfile',
            name='is_archive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='downloaderjoboriginalfileassociation',
            name='original_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.OriginalFile'),
        ),
    ]
