# Generated by Django 2.1.8 on 2019-08-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0030_update_sample_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismindex',
            name='salmon_version',
            field=models.CharField(default='salmon 0.13.1', max_length=255),
        ),
    ]
