# Generated by Django 2.0.2 on 2018-02-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0030_auto_20180214_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaderjob',
            name='accession_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
