# Generated by Django 2.1.8 on 2019-09-13 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0031_auto_20190823_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyedAccession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_code', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'surveyed_accessions',
            },
        ),
    ]
