# Generated by Django 2.0.2 on 2018-02-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0031_downloaderjob_accession_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloaderjob',
            name='original_file',
        ),
    ]
