# Generated by Django 2.0.2 on 2018-02-14 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0032_remove_downloaderjob_original_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorJobOriginalFileAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.OriginalFile')),
                ('processor_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.ProcessorJob')),
            ],
            options={
                'db_table': 'processorjob_originalfile_associations',
            },
        ),
        migrations.RemoveField(
            model_name='processorjobsampleassociation',
            name='processor_job',
        ),
        migrations.RemoveField(
            model_name='processorjobsampleassociation',
            name='sample',
        ),
        migrations.DeleteModel(
            name='ProcessorJobSampleAssociation',
        ),
    ]
