# Generated by Django 2.0.2 on 2018-02-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0033_auto_20180214_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalfile',
            name='source_absolute_file_path',
        ),
    ]
