# Generated by Django 2.1.8 on 2019-09-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0034_dataset_include_quant_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedfile',
            name='quant_sf_only',
            field=models.BooleanField(default=False),
        ),
    ]
