# Generated by Django 2.0.2 on 2018-02-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0034_remove_originalfile_source_absolute_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedfile',
            name='size_in_bytes',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='originalfile',
            name='size_in_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
