# Generated by Django 2.0.2 on 2018-02-15 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0035_auto_20180215_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalfile',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Sample'),
        ),
    ]
