# Generated by Django 2.0.2 on 2018-02-16 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0037_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='compultationalresultannotation',
            name='key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compultationalresultannotation',
            name='result',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.ComputationalResult'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compultationalresultannotation',
            name='value',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computationalresult',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computationalresult',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
