# Generated by Django 2.1.8 on 2019-09-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0038_paginate_default_svd_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedfile',
            name='svd_algorithm',
            field=models.CharField(choices=[('NONE', 'None'), ('RANDOMIZED', 'randomized'), ('ARPACK', 'arpack')], default='NONE', help_text='The SVD algorithm that was used to generate the file.', max_length=255),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='svd_algorithm',
            field=models.CharField(choices=[('NONE', 'None'), ('RANDOMIZED', 'randomized'), ('ARPACK', 'arpack')], default='NONE', help_text='Specifies choice of SVD algorithm', max_length=255),
        ),
    ]
