# Generated by Django 2.0.2 on 2018-02-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0038_auto_20180216_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='version',
            new_name='source_version',
        ),
    ]
