# Generated by Django 2.1.8 on 2019-09-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0038_paginate_default_svd_algorithm'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='computedfile',
            name='computed_fi_filenam_64958d_idx',
        ),
    ]
