# Generated by Django 2.0.2 on 2018-02-20 15:26

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0040_auto_20180219_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compultationalresultannotation',
            name='key',
        ),
        migrations.RemoveField(
            model_name='compultationalresultannotation',
            name='value',
        ),
        migrations.AddField(
            model_name='compultationalresultannotation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='compultationalresultannotation',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
        migrations.AddField(
            model_name='compultationalresultannotation',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compultationalresultannotation',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
