# Generated by Django 2.0.2 on 2018-02-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0041_auto_20180220_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedfile',
            name='s3_bucket',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='computedfile',
            name='s3_key',
            field=models.CharField(max_length=255),
        ),
    ]
