# Generated by Django 2.1.8 on 2019-11-02 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0041_auto_20190925_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompendiaResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_sf_only', models.BooleanField(default=False)),
                ('compendia_version', models.IntegerField(blank=True, null=True)),
                ('svd_algorithm', models.CharField(choices=[('NONE', 'None'), ('RANDOMIZED', 'randomized'), ('ARPACK', 'arpack')], default='NONE', help_text='The SVD algorithm that was used to impute the compendia result.', max_length=255)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'compendia_results',
                'base_manager_name': 'public_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('public_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CompendiaResultOrganismAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compendia_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.CompendiaResult')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Organism')),
            ],
            options={
                'db_table': 'compendia_result_organism_associations',
            },
        ),
        migrations.AddField(
            model_name='compendiaresult',
            name='organisms',
            field=models.ManyToManyField(related_name='compendia_results', through='data_refinery_common.CompendiaResultOrganismAssociation', to='data_refinery_common.Organism'),
        ),
        migrations.AddField(
            model_name='compendiaresult',
            name='primary_organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_compendia_results', to='data_refinery_common.Organism'),
        ),
        migrations.AddField(
            model_name='compendiaresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compendia_result', to='data_refinery_common.ComputationalResult'),
        ),
        migrations.AlterUniqueTogether(
            name='compendiaresultorganismassociation',
            unique_together={('compendia_result', 'organism')},
        ),
    ]
