# Generated by Django 2.1.8 on 2019-10-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0041_auto_20190925_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismComputedFileAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.ComputedFile')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_common.Organism')),
            ],
            options={
                'db_table': 'organism_computed_file_associations',
            },
        ),
        migrations.AddField(
            model_name='computedfile',
            name='compendia_organisms',
            field=models.ManyToManyField(related_name='new_compendia_organisms', through='data_refinery_common.OrganismComputedFileAssociation', to='data_refinery_common.Organism'),
        ),
        migrations.AlterUniqueTogether(
            name='organismcomputedfileassociation',
            unique_together={('organism', 'computed_file')},
        ),
    ]
