# Generated by Django 2.1.8 on 2019-11-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0042_remove_experiment_organism_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorjob',
            name='abort',
            field=models.BooleanField(default=False),
        ),
    ]
