# Generated by Django 2.2.10 on 2020-05-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0054_datasetannotation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasetannotation", options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(name="datasetannotation", managers=[],),
        migrations.AlterField(
            model_name="datasetannotation",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
