# Generated by Django 2.2.13 on 2020-08-12 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0058_auto_20200625_1402"),
    ]

    operations = [
        migrations.CreateModel(
            name="OntologyTerm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ontology_term", models.TextField(unique=True)),
                ("human_readable_name", models.TextField()),
            ],
            options={"db_table": "ontology_terms",},
        ),
        migrations.CreateModel(
            name="SampleAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("probability", models.FloatField(null=True)),
                ("source", models.TextField()),
                (
                    "value_type",
                    models.TextField(
                        choices=[
                            ("bool", "Boolean"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("ont", "Ontology Term"),
                        ]
                    ),
                ),
                ("value", models.TextField()),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data_refinery_common.OntologyTerm",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="data_refinery_common.Sample",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data_refinery_common.OntologyTerm",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ExperimentAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("probability", models.FloatField(null=True)),
                ("source", models.TextField()),
                (
                    "value_type",
                    models.TextField(
                        choices=[
                            ("bool", "Boolean"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("ont", "Ontology Term"),
                        ]
                    ),
                ),
                ("value", models.TextField()),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="data_refinery_common.Experiment",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data_refinery_common.OntologyTerm",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data_refinery_common.OntologyTerm",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
