# Generated by Django 2.2.13 on 2020-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0058_auto_20200625_1402"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloaderjob",
            name="volume_index",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="processorjob",
            name="volume_index",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
