# Generated by Django 2.2.13 on 2020-08-19 16:32

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0058_auto_20200625_1402"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_name", models.TextField()),
                ("methods_url", models.URLField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OntologyTerm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ontology_term", models.TextField(unique=True)),
                ("human_readable_name", models.TextField()),
            ],
            options={"db_table": "ontology_terms",},
        ),
        migrations.AddField(
            model_name="experiment",
            name="sample_keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="downloaderjob",
            name="volume_index",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="processorjob",
            name="volume_index",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.CreateModel(
            name="SampleKeyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data_refinery_common.OntologyTerm",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="data_refinery_common.Sample",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_refinery_common.Contribution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("probability", models.FloatField(null=True)),
                (
                    "value_type",
                    models.TextField(
                        choices=[
                            ("bool", "Boolean"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("ont", "Ontology Term"),
                        ]
                    ),
                ),
                ("value", models.TextField()),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data_refinery_common.OntologyTerm",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="data_refinery_common.Sample",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_refinery_common.Contribution",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data_refinery_common.OntologyTerm",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ExperimentAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("probability", models.FloatField(null=True)),
                (
                    "value_type",
                    models.TextField(
                        choices=[
                            ("bool", "Boolean"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("ont", "Ontology Term"),
                        ]
                    ),
                ),
                ("value", models.TextField()),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="data_refinery_common.Experiment",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data_refinery_common.OntologyTerm",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_refinery_common.Contribution",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data_refinery_common.OntologyTerm",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
