# Generated by Django 2.2.13 on 2020-08-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0059_auto_20200819_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organismindex',
            old_name='source_version',
            new_name='ensembl_release',
        ),
    ]
