# Generated by Django 2.2.13 on 2020-08-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0061_transcriptome_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismindex',
            name='database_name',
            field=models.CharField(max_length=255),
        ),
    ]
