# Generated by Django 2.2.13 on 2021-02-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0062_auto_20200828_2103"),
    ]

    operations = [
        migrations.AddField(
            model_name="organism",
            name="has_compendia",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="organism",
            name="has_quantfile_compendia",
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
