# Generated by Django 2.2.13 on 2021-02-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0063_auto_20210212_1855"),
    ]

    operations = [
        migrations.AlterModelOptions(name="dataset", options={"base_manager_name": "objects"},),
    ]
