# Generated by Django 2.2.13 on 2021-04-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0066_surveyjob_retried_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyjob", name="ram_amount", field=models.IntegerField(default=1024),
        ),
    ]
