# Generated by Django 2.2.13 on 2021-05-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0067_auto_20210429_1557"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloaderjob",
            name="batch_job_queue",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="processorjob",
            name="batch_job_queue",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="processorjob",
            name="downloader_job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_refinery_common.DownloaderJob",
            ),
        ),
        migrations.AddField(
            model_name="surveyjob",
            name="batch_job_queue",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
