# Generated by Django 3.2.4 on 2021-09-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0068_auto_20210729_1610"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computedfile",
            old_name="compendia_version",
            new_name="compendium_version",
        ),
    ]
