# Generated by Django 3.2.7 on 2022-05-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_common', '0070_auto_20211208_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitoken',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='compendiumresult',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='computationalresult',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='computationalresultannotation',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='computedfile',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='datasetannotation',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='downloaderjob',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='source_last_modified',
            new_name='source_last_modified_at',
        ),
        migrations.RenameField(
            model_name='experimentannotation',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='organism',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='organismindex',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='originalfile',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='processorjob',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='sampleannotation',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='surveyjob',
            old_name='last_modified',
            new_name='last_modified_at',
        ),
    ]
