# Generated by Django 3.2.7 on 2022-09-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0071_gatheredaccession"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gatheredaccession",
            index=models.Index(fields=["accession_code"], name="gathered_ac_accessi_5dde9a_idx"),
        ),
        migrations.AddIndex(
            model_name="gatheredaccession",
            index=models.Index(fields=["created_at"], name="gathered_ac_created_2efd0f_idx"),
        ),
    ]
