# Generated by Django 3.2.18 on 2023-10-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0072_auto_20220927_2235"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="genotype",
            new_name="genetic_information",
        ),
    ]
