# Generated by Django 3.2.18 on 2023-10-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0073_rename_genotype_sample_genetic_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="developmental_stage",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
