# Generated by Django 3.2.18 on 2023-12-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_refinery_common", "0074_sample_developmental_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="last_refreshed",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
