FROM ccdlstaging/dr_affymetrix:latest

USER root

COPY common/dist/data-refinery-common-* common/
# Get the latest version from the dist directory.
RUN pip3 install common/$(ls common -1 | sort --version-sort | tail -1)

ARG SYSTEM_VERSION

ENV SYSTEM_VERSION $SYSTEM_VERSION

USER user

COPY config/ config/
COPY workers/ .

ENTRYPOINT []
