# Turn warnings into errors because biocLite throws warnings instead # of error if it fails to install something.
options(warn=2)
options(repos=structure(c(CRAN="https://cloud.r-project.org")))
options(Ncpus=parallel::detectCores())

# Bioconductor packages, installed by devtools::install_url()

# Helper function that installs a list of packages using the input URLs
install_with_url <- function(urls) {
  pkg_ids <- devtools::install_url(urls)
  if(any(is.na(pkg_ids))) {
    pkg_fails <- paste(urls[is.na(pkg_ids)], collapse = "; ")
    stop(paste("Failed to install package(s):", pkg_fails ))
  }
  return(pkg_ids)
}

devtools::install_version('dplyr', version='1.0.2')

bioc_pkg_urls <- c(
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/oligoClasses_1.50.4.tar.gz',
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/oligo_1.52.1.tar.gz',
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/GEOquery_2.56.0.tar.gz',
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/SCAN.UPC_2.30.0.tar.gz',
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/affy_1.66.0.tar.gz',
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/affyio_1.58.0.tar.gz',
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/AnnotationDbi_1.50.3.tar.gz',
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/zlibbioc_1.34.0.tar.gz',
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/preprocessCore_1.50.0.tar.gz',
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/genefilter_1.70.0.tar.gz',
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/sva_3.36.0.tar.gz',
  'https://bioconductor.org/packages/3.11/bioc/src/contrib/limma_3.44.3.tar.gz'
)
install_with_url(bioc_pkg_urls)

# Invoke another R script to install BrainArray ensg packages
source("install_ensg_pkgs.R")

# Install Bioconductor platform design (pd) packages
pd_experiment_pkgs <- c(
  'https://bioconductor.org/packages/3.11/data/experiment/src/contrib/pd.atdschip.tiling_0.26.0.tar.gz'
)
install_with_url(pd_experiment_pkgs)

pd_annotation_pkgs <- c(
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.081229.hg18.promoter.medip.hx1_0.99.4.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.2006.07.18.hg18.refseq.promoter_1.8.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.2006.07.18.mm8.refseq.promoter_0.99.3.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.2006.10.31.rn34.refseq.promoter_0.99.3.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ag_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.aragene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.aragene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ath1.121501_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.barley1_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.bovgene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.bovgene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.bovine_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.bsubtilis_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.cangene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.cangene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.canine_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.canine.2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.celegans_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.charm.hg18.example_0.99.4.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.chicken_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.chigene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.chigene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.chogene.2.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.chogene.2.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.citrus_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.clariom.d.human_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.clariom.s.human_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.clariom.s.human.ht_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.clariom.s.mouse_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.clariom.s.mouse.ht_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.clariom.s.rat_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.clariom.s.rat.ht_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.cotton_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.cyngene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.cyngene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.cyrgene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.cyrgene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.cytogenetics.array_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.drogene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.drogene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.drosgenome1_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.drosophila.2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.e.coli.2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ecoli_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ecoli.asv2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.elegene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.elegene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.equgene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.equgene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.feinberg.hg18.me.hx1_0.99.3.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.feinberg.mm8.me.hx1_0.99.3.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.felgene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.felgene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.fingene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.fingene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.genomewidesnp.5_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.genomewidesnp.6_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.guigene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.guigene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hc.g110_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.focus_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u133.plus.2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u133a_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u133a.2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u133a.tag_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u133b_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u219_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u95a_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u95av2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u95b_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u95c_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u95d_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg.u95e_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hg18.60mer.expr_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ht.hg.u133.plus.pm_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ht.hg.u133a_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ht.mg.430a_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hta.2.0_3.12.2.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hu6800_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.huex.1.0.st.v2_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hugene.1.0.st.v1_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hugene.1.1.st.v1_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hugene.2.0.st_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.hugene.2.1.st_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.maize_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mapping250k.nsp_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mapping250k.sty_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mapping50k.hind240_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mapping50k.xba240_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.margene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.margene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.medgene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.medgene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.medicago_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mg.u74a_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mg.u74av2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mg.u74b_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mg.u74bv2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mg.u74c_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mg.u74cv2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mirna.1.0_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mirna.2.0_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mirna.3.0_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mirna.3.1_3.8.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mirna.4.0_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.moe430a_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.moe430b_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.moex.1.0.st.v1_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mogene.1.0.st.v1_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mogene.1.1.st.v1_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mogene.2.0.st_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mogene.2.1.st_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mouse430.2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mouse430a.2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mta.1.0_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mu11ksuba_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.mu11ksubb_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.nugo.hs1a520180_3.4.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.nugo.mm1a520177_3.4.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ovigene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ovigene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.pae.g1a_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.plasmodium.anopheles_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.poplar_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.porcine_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.porgene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.porgene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rabgene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rabgene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rae230a_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rae230b_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.raex.1.0.st.v1_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ragene.1.0.st.v1_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ragene.1.1.st.v1_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ragene.2.0.st_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.ragene.2.1.st_3.14.1.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rat230.2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rcngene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rcngene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rg.u34a_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rg.u34b_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rg.u34c_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rhegene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rhegene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rhesus_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rice_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rjpgene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rjpgene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rn.u34_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rta.1.0_3.12.2.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rusgene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.rusgene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.s.aureus_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.soybean_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.soygene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.soygene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.sugar.cane_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.tomato_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.u133.x3p_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.vitis.vinifera_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.wheat_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.x.laevis.2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.x.tropicalis_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.xenopus.laevis_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.yeast.2_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.yg.s98_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.zebgene.1.0.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.zebgene.1.1.st_3.12.0.tar.gz',
  'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/pd.zebrafish_3.12.0.tar.gz'
)
install_with_url(pd_annotation_pkgs)

# Load this libraries because apparently just installing it isn't
# enough to verify that the correct versions of dependencies are installed.
library('foreach')
