FROM continuumio/miniconda3:4.3.11

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

COPY workers/environment.yml .

RUN conda env create -f environment.yml

ENV PATH "/opt/conda/envs/workers/bin:$PATH"

COPY data_models/dist/data-refinery-models-* data_models/

# Get the latest version from the dist directory.
RUN pip install data_models/$(ls data_models -1 | sort --version-sort | tail -1)

COPY common/dist/data-refinery-common-* common/

# Get the latest version from the dist directory.
RUN pip install common/$(ls common -1 | sort --version-sort | tail -1)

COPY workers/ .

USER user

ENTRYPOINT ["python3.6", "manage.py"]

CMD ["test", "--no-input"]
