options(repos=structure(c(CRAN="https://cloud.r-project.org")))

# Install dev packages
install.packages("devtools")
install.packages("dplyr")

devtools::install_version('data.table', version='1.11.0')
devtools::install_version('optparse', version='1.4.4')

source('https://bioconductor.org/biocLite.R')

# biocLite("cangene10st.db")
# biocLite("clariomsrat.db")
# biocLite("ragene21st.db")
# biocLite("hugene20st.db")
# biocLite("mouse430a2.db")
# biocLite("porgene11st.db")
# biocLite("ovigene11st.db")
# biocLite("rgu34c.db")
# biocLite("htmg430b.db")
# biocLite("mogene11st.db")
# biocLite("htmg430pm.db")
# biocLite("clariomshumanht.db")
# biocLite("rgu34a.db")
# biocLite("hgu95e.db")
# biocLite("yeast2.db")
# biocLite("primeview_spikeins.db")
# biocLite("clariomshuman.db")
# biocLite("mogene10st.db")
# biocLite("ragene20st.db")
# biocLite("elegene11st.db")
# biocLite("hgu133plus2.db")
# biocLite("hgu95d.db")
# biocLite("porgene10st.db")
# biocLite("canine2.db")
# biocLite("hugene10st.db")
# biocLite("hgu133a2.db")
# biocLite("htmg430a.db")
# biocLite("celegans.db")
# biocLite("zebrafish.db")
# biocLite("hugene21st.db")
# biocLite("moe430a.db")
# biocLite("ovigene10st.db")
# biocLite("mouse4302.db")
# biocLite("ragene11st.db")
# biocLite("elegene10st.db")
# biocLite("hgu133b.db")
# biocLite("bovgene11st.db")
# biocLite("ragene10st.db")
# biocLite("chigene11st.db")
# biocLite("u133aaofav2.db")
# biocLite("mu11ksuba.db")
# biocLite("snowballs520824f.db")
# biocLite("drosophila2.db")
# biocLite("rat2302.db")
# biocLite("hgu133a.db")
# biocLite("canine.db")
# biocLite("primeview.db")
# biocLite("mgu74cv2.db")
# biocLite("hgu95av2.db")
# biocLite("rae230b.db")
# biocLite("bovine.db")
# biocLite("mogene20st.db")
# biocLite("bovgene10st.db")
# biocLite("equgene11st.db")
# biocLite("hthgu133pluspm.db")
# biocLite("rhesus.db")
# biocLite("hgu219.db")
# biocLite("chigene10st.db")
# biocLite("clariomsmouse.db")
# biocLite("zebgene11st.db")
# biocLite("hthgu133b.db")
# biocLite("hgu95a.db")
# biocLite("mogene21st.db")
# biocLite("ygs98.db")
# biocLite("clariomdhuman.db")
# biocLite("hta20.db")
# biocLite("mu11ksubb.db")
# biocLite("chicken.db")
# biocLite("equgene10st.db")
# biocLite("porcine.db")
# biocLite("rgu34b.db")
# biocLite("drogene10st.db")
# biocLite("htratfocus.db")
# biocLite("mgu74a.db")
# biocLite("hthgu133a.db")
# biocLite("mgu74bv2.db")
# biocLite("cangene11st.db")
# biocLite("rae230a.db")
# biocLite("hgu95b.db")
# biocLite("hugene11st.db")
# biocLite("moe430b.db")
# biocLite("hgu95c.db")
# biocLite("zebgene10st.db")
# biocLite("drosgenome1.db")
# biocLite("htrat230pm.db")
# biocLite("drogene11st.db")
# biocLite("mgu74av2.db")

install.packages("tidyverse")
install.packages("rlang")
