variable "data_refinery_vpc" { default = "" }
variable "data_refinery_subnet" { default = "" }
variable "data_refinery_bucket" { default = "" }
variable "data_refinery_results_bucket" { default = "" }
variable "data_refinery_transcriptome_index_bucket" { default = "" }
variable "data_refinery_qn_target_bucket" { default = "" }
variable "data_refinery_compendia_bucket" { default = "" }
# variable "data_refinery_worker_profile" { default = "" }
variable "data_refinery_spot_fleet_role" { default = "" }
variable "data_refinery_keypair" { default = "" }
variable "data_refinery_worker_security_group" { default = "" }
variable "data_refinery_worker_user_data" { default = "" }
variable "data_refinery_worker_ami" { default = "" }
variable "user" { default = "" }
variable "stage" { default = "" }
variable "region" { default = "" }
