# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloaderJobsToBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_refinery_models.Batch')),
            ],
            options={
                'db_table': 'downloader_jobs_to_batches',
            },
        ),
        migrations.CreateModel(
            name='ProcessorJobsToBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_refinery_models.Batch')),
            ],
            options={
                'db_table': 'processor_jobs_to_batches',
            },
        ),
        migrations.RemoveField(
            model_name='downloaderjob',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='processorjob',
            name='batch',
        ),
        migrations.AddField(
            model_name='processorjobstobatches',
            name='processor_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_refinery_models.ProcessorJob'),
        ),
        migrations.AddField(
            model_name='downloaderjobstobatches',
            name='downloader_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_refinery_models.DownloaderJob'),
        ),
    ]
