# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_models', '0002_auto_20170320_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='download_url',
            field=models.CharField(max_length=2048),
        ),
    ]
