# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_models', '0002_auto_20170626_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaderjob',
            name='retried',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processorjob',
            name='retried',
            field=models.BooleanField(default=False),
        ),
    ]
