# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_models', '0002_surveyjob_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyJobKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('survey_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_models.SurveyJob')),
            ],
            options={
                'db_table': 'survey_job_key_values',
            },
        ),
        migrations.RenameField(
            model_name='batchkeyvalue',
            old_name='batch_id',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='downloaderjob',
            old_name='batch_id',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='processorjob',
            old_name='batch_id',
            new_name='batch',
        ),
    ]
