# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_models', '0002_auto_20170509_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='survey_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_refinery_models.SurveyJob'),
        ),
        migrations.AlterField(
            model_name='downloaderjobstobatches',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_models.Batch'),
        ),
        migrations.AlterField(
            model_name='downloaderjobstobatches',
            name='downloader_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_models.DownloaderJob'),
        ),
        migrations.AlterField(
            model_name='processorjobstobatches',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_models.Batch'),
        ),
        migrations.AlterField(
            model_name='processorjobstobatches',
            name='processor_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_refinery_models.ProcessorJob'),
        ),
    ]
