# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_models', '0003_auto_20170809_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='size_in_bytes',
            field=models.BigIntegerField(),
        ),
    ]
