# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_models', '0003_auto_20170331_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaderjob',
            name='worker_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='processorjob',
            name='worker_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
