# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_models', '0004_auto_20170410_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=256)),
                ('taxonomy_id', models.IntegerField()),
                ('is_scientific_name', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'organisms',
            },
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='organism',
            new_name='organism_id',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='accession_code',
            new_name='platform_accession_code',
        ),
        migrations.AddField(
            model_name='batch',
            name='experiment_accession_code',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='experiment_title',
            field=models.CharField(default=' ', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='file_name',
            field=models.CharField(default='temp', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='last_uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 24, 19, 24, 54, 4858, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='organism_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 24, 19, 25, 9, 620286, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
