# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_models', '0005_auto_20170424_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='file_name',
            new_name='name',
        ),
    ]
