# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_models', '0006_auto_20170427_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='experiment_title',
            field=models.CharField(max_length=256),
        ),
    ]
