# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_refinery_models', '0007_auto_20170427_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='last_uploaded_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='release_date',
            field=models.DateField(),
        ),
    ]
