name: Analysis Tools

on:
  workflow_dispatch:
    inputs:
      tool:
        description: Analysis tool to run
        required: true
        type: choice
        options:
          - infrascan

jobs:
  infrascan:
    if: ${{ github.event.inputs.tool == 'infrascan' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Reports Directory
        run: mkdir -p infrascan-reports

      - name: Run InfraScan
        uses: soldevelo/infrascan@v1.0.9
        with:
          scanner: comprehensive
          format: html
          out: infrascan-reports/report.html

      - name: Upload InfraScan Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: infrascan-report
          path: infrascan-reports/report.html
          retention-days: 14
