from data_refinery_api.views_2.jobs.downloader_job import DownloaderJobListView
from data_refinery_api.views_2.jobs.processor_job import ProcessorJobListView
from data_refinery_api.views_2.jobs.survey_job import SurveyJobListView
